-- USE cdrg;

DROP TABLE IF EXISTS raw_contracts;

CREATE TABLE raw_contracts (
	unique_transaction_id  BINARY(16) /*PRIMARY KEY*/, -- Field 0
	-- transaction_status varchar(45),
	obligatedamount decimal(25,2), -- Field 2
	-- baseandexercisedoptionsvalue varchar(45), -- Field 3
	-- baseandalloptionsvalue varchar(45), -- Field 4
	maj_agency_cat varchar(100), -- Field 5
	/* mod_agency varchar(45),
	maj_fund_agency_cat varchar(45),
	contractingofficeagencyid varchar(45),
	contractingofficeid varchar(45),
	fundingrequestingagencyid varchar(45),
	fundingrequestingofficeid varchar(45),
	fundedbyforeignentity varchar(45),
	signeddate date, */
	effectivedate date,  -- Field 14
	-- currentcompletiondate date,  -- Field 15
	ultimatecompletiondate date,  -- Field 16
	/* lastdatetoorder date,
	contractactiontype varchar(45),
	reasonformodification varchar(45),
	typeofcontractpricing varchar(45),
	priceevaluationpercentdifference varchar(10),
	subcontractplan varchar(100),
	type_of_contract varchar(50),
	lettercontract varchar(100),
	multiyearcontract varchar(100),
	performancebasedservicecontract varchar(100),
	majorprogramcode varchar(100),
	contingencyhumanitarianpeacekeepingoperation varchar(100),
	contractfinancing varchar(100),
	costorpricingdata varchar(100),
	costaccountingstandardsclause varchar(100), */
	descriptionofcontractrequirement varchar(65000), -- Field 32
	/* purchasecardaspaymentmethod varchar(100),
	numberofactions varchar(100),
	nationalinterestactioncode varchar(100),
	progsourceagency varchar(100),
	progsourceaccount varchar(100),
	progsourcesubacct varchar(100), */
	account_title varchar(250), -- Field 39
	/* rec_flag varchar(100),
	typeofidc varchar(100),
	multipleorsingleawardidc varchar(100),
	programacronym varchar(100), */
	vendorname varchar(150), -- Field 44
	vendoralternatename varchar(150),
	vendorlegalorganizationname varchar(150),
	vendordoingasbusinessname varchar(150),
	/* divisionname varchar(100),
	divisionnumberorofficecode varchar(100),
	vendorenabled varchar(100),
	vendorlocationdisableflag varchar(100),
	ccrexception varchar(100),*/
	streetaddress varchar(150), -- Field 53
	streetaddress2 varchar(150),
	streetaddress3 varchar(150),
	city varchar(100),
	state varchar(50),
	zipcode varchar(50),
	vendorcountrycode varchar(10),  -- Field 59
	vendor_state_code varchar(50),
	vendor_cd varchar(50), -- Field 61
	/* congressionaldistrict varchar(100),
	vendorsitecode varchar(100),
	vendoralternatesitecode varchar(100), */
	dunsnumber varchar(50), -- Field 65
	parentdunsnumber varchar(50),
	phoneno varchar(50),
	faxno varchar(50), -- Field 68
	/* registrationdate varchar(100),
	renewaldate varchar(100),
	mod_parent varchar(100),
	locationcode varchar(100),
	statecode varchar(100),
	pop_state_code varchar(100),
	placeofperformancecountrycode varchar(100),
	placeofperformancezipcode varchar(100),
	pop_cd varchar(100),
	placeofperformancecongressionaldistrict varchar(100), */
	psc_cat varchar(150), -- Field 79
	productorservicecode varchar(450), -- Field 80
	/* systemequipmentcode varchar(100),
	claimantprogramcode varchar(100),
	principalnaicscode varchar(100),
	informationtechnologycommercialitemcategory varchar(100),
	gfe_gfp varchar(100),
	useofepadesignatedproducts varchar(100),
	recoveredmaterialclauses varchar(100),
	seatransportation varchar(100),
	contractbundling varchar(100),
	consolidatedcontract varchar(100),
	countryoforigin varchar(100),
	placeofmanufacture varchar(100),
	manufacturingorganizationtype varchar(100),
	agencyid varchar(100),
	piid varchar(100),
	modnumber varchar(100),
	transactionnumber varchar(100), */
	fiscal_year SMALLINT UNSIGNED, -- Field 98
	/* idvagencyid varchar(100),
	idvpiid varchar(100),
	idvmodificationnumber varchar(100),
	solicitationid varchar(100),
	extentcompeted varchar(100),
	reasonnotcompeted varchar(100),
	numberofoffersreceived varchar(100),
	commercialitemacquisitionprocedures varchar(100),
	commercialitemtestprogram varchar(100),
	smallbusinesscompetitivenessdemonstrationprogram varchar(100),
	a76action varchar(100),
	competitiveprocedures varchar(100),
	solicitationprocedures varchar(100),
	typeofsetaside varchar(100),
	localareasetaside varchar(100),
	evaluatedpreference varchar(100),
	fedbizopps varchar(100),
	research varchar(100),
	statutoryexceptiontofairopportunity varchar(100),
	organizationaltype varchar(100), */
	numberofemployees INT UNSIGNED, -- Field 119
	annualrevenue BIGINT UNSIGNED, -- Field 120
	/* firm8aflag varchar(100),
	hubzoneflag varchar(100),
	sdbflag varchar(100),
	issbacertifiedsmalldisadvantagedbusiness varchar(100),
	shelteredworkshopflag varchar(100),
	hbcuflag varchar(100),
	educationalinstitutionflag varchar(100),
	womenownedflag varchar(100),
	veteranownedflag varchar(100),
	srdvobflag varchar(100),
	localgovernmentflag varchar(100),
	minorityinstitutionflag varchar(100),
	aiobflag varchar(100),
	stategovernmentflag varchar(100),
	federalgovernmentflag varchar(100),
	minorityownedbusinessflag varchar(100),
	apaobflag varchar(100),
	tribalgovernmentflag varchar(100),
	baobflag varchar(100),
	naobflag varchar(100),
	saaobflag varchar(100),
	nonprofitorganizationflag varchar(100),
	isothernotforprofitorganization varchar(100),
	isforprofitorganization varchar(100),
	isfoundation varchar(100),
	haobflag varchar(100),
	ishispanicservicinginstitution varchar(100),
	verysmallbusinessflag varchar(100),
	hospitalflag varchar(100),
	contractingofficerbusinesssizedetermination varchar(100),
	is1862landgrantcollege varchar(100),
	is1890landgrantcollege varchar(100),
	is1994landgrantcollege varchar(100),
	isveterinarycollege varchar(100),
	isveterinaryhospital varchar(100),
	isprivateuniversityorcollege varchar(100),
	isschoolofforestry varchar(100),
	isstatecontrolledinstitutionofhigherlearning varchar(100),
	isserviceprovider varchar(100),
	receivescontracts varchar(100),
	receivesgrants varchar(100),
	receivescontractsandgrants varchar(100),
	isairportauthority varchar(100),
	iscouncilofgovernments varchar(100),
	ishousingauthoritiespublicortribal varchar(100),
	isinterstateentity varchar(100),
	isplanningcommission varchar(100),
	isportauthority varchar(100),
	istransitauthority varchar(100),
	issubchapterscorporation varchar(100),
	islimitedliabilitycorporation varchar(100),
	isforeignownedandlocated varchar(100),
	isarchitectureandengineering varchar(100),
	isdotcertifieddisadvantagedbusinessenterprise varchar(100),
	iscitylocalgovernment varchar(100),
	iscommunitydevelopedcorporationownedfirm varchar(100),
	iscommunitydevelopmentcorporation varchar(100),
	isconstructionfirm varchar(100),
	ismanufacturerofgoods varchar(100),
	iscorporateentitynottaxexempt varchar(100),
	iscountylocalgovernment varchar(100),
	isdomesticshelter varchar(100),
	isfederalgovernmentagency varchar(100),
	isfederallyfundedresearchanddevelopmentcorp varchar(100),
	isforeigngovernment varchar(100),
	isindiantribe varchar(100),
	isintermunicipallocalgovernment varchar(100),
	isinternationalorganization varchar(100),
	islaborsurplusareafirm varchar(100),
	islocalgovernmentowned varchar(100),
	ismunicipalitylocalgovernment varchar(100),
	isnativehawaiianownedorganizationorfirm varchar(100),
	isotherbusinessororganization varchar(100),
	isotherminorityowned varchar(100),
	ispartnershiporlimitedliabilitypartnership varchar(100),
	isschooldistrictlocalgovernment varchar(100),
	issmallagriculturalcooperative varchar(100),
	issoleproprietorship varchar(100),
	istownshiplocalgovernment varchar(100),
	istriballyownedfirm varchar(100),
	istribalcollege varchar(100),
	isalaskannativeownedcorporationorfirm varchar(100),
	iscorporateentitytaxexempt varchar(100),
	walshhealyact varchar(100),
	servicecontractact varchar(100),
	davisbaconact varchar(100),
	clingercohenact varchar(100),
	otherstatutoryauthority varchar(100),
	interagencycontractingauthority varchar(100) */
  org_id BIGINT NULL,
  agency_org_id BIGINT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;